version: '3.8'

services:
  job-dorker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: job-dorker-app
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
      - HOST=0.0.0.0
      - PORT=3001
      - DATABASE_URL=sqlite:/app/data/jobs.db
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./data:/app/data
      - ./reports:/app/reports
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - job-dorker-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    container_name: job-dorker-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - job-dorker-network
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s

  # Optional: Redis Commander for Redis management
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: job-dorker-redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - job-dorker-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    profiles:
      - tools

volumes:
  redis_data:
    driver: local

networks:
  job-dorker-network:
    driver: bridge
