version: '3.8'

services:
  job-dorker-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: job-dorker-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - LOG_PRETTY=true
      - DATABASE_URL=sqlite:/app/data/jobs.db
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/app
      - /app/node_modules
      - ./data:/app/data
      - ./reports:/app/reports
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - job-dorker-dev-network
    command: npm run dev

  redis:
    image: redis:7-alpine
    container_name: job-dorker-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    restart: unless-stopped
    networks:
      - job-dorker-dev-network
    command: redis-server --appendonly yes

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: job-dorker-redis-commander-dev
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - job-dorker-dev-network

volumes:
  redis_dev_data:
    driver: local

networks:
  job-dorker-dev-network:
    driver: bridge
